import { Injectable } from '@angular/core';

@Injectable()
export class LanpackService {

/*
  en = english
  fi = finnish
  se = swedish
*/
  strings: any = {
    // english
    en: {
      admistrationExpenses: "Admistration expenses",
      appropriationsIncome: "Appropriations (income)",
      apartmentExpenses: "Apartment expenses",
      appropriations: "Appropriations",
      appropriationsExpense: "Appropriations (expense)",
      assets: "Assets",
      assetsTotal: "Assets total",
      balanceSheet: "Balance sheet",
      buildings: "Buildings",
      capital: "Capital and reserves",
      capitalAndReserves: "Capital and reserves",
      capitalAndReservesTotal: "Capital and reserves, Total",
      cashInHandAndInBank: "Cash in hand and in bank",
      cashOrBank: "Cash or bank",
      computerDeviceAndSoftware: "Computer device and software",
      creditors: "Creditors",
      creditorsTotal: "Creditors total",
      currentAssets: "Current assets",
      currentAssetsTotal: "Current assets, total",
      debtor: "Current assets",
      debtors: "Debtors",
      debosit: "Deposit",
      debositOrWithdrawal: "Deposit or withdrawal",
      delete: "Delete",
      depreciationsAccordingToPlan: "Depreciations according to plan",
      depreciationsAndReductionsInValue: "Depreciations and reductions in value",
      depreciationsAndReductionsInValueTotal: "Depreciations and reductions in value, total",
      equityAndLiabilities: "Equity and liabilities",
      equityAndLiabilitiesTotal: "Equity and liabilities, total",
      externalServices: "External services",
      financialExpenses: "Financial expenses",
      financialIncome: "Financial income",
      income: "Income",
      incomeTaxes: "Income taxes",
      intangibleAssets: "Intangible assets",
      investments: "Investments",
      loanOrDebt: "Creditors",
      loans: "loans",
      loansFromCreditInstitutions: "Loans from credit institutions",
      longterm: "Longterm",
      longtermExpenses: "Non-current assets",
      machineryAndEquipment: "Machinery and equipment",
      nonCurrentAssets: "Non-current assets",
      nonCurrentAssetsTotal: "Non-current assets total",
      operatingProfitLoss: "Operating profit (loss)",
      optionalStaffExpenses: "Optional staff expenses",
      otherCreditors: "Other creditors",
      otherOperatingExpenses: "Other operating expenses",
      otherOperatingExpensesTotal: "Other operating expenses, total",
      otherOperatingIncome: "Other operating income",
      otherReceivables: "Other receivables",
      otherReserves: "Other reserves",
      otherSocialSecurityExpenses: "Other social security expenses",
      passedData: "Passed data",
      pensionExpenses: "Pension expenses",
      price: "Price",
      profitAndLossAccount: "Profit and loss account",
      profitLossBeforeAppropriationsAndTaxes: "Profit (loss) before appropriations and taxes",
      profitLossOfTheFinancialYear: "Profit (loss) of the financial year",
      provisions: "Provisions",
      purchasesDuringTheFinancialYear: "Purchases during the financial year",
      purchasesDuringTheFinancialYearTradeCreditors: "Purchases during the financial year, trade creditors",
      rawMaterialsAndConsumables: "Raw materials and consumables",
      rawMaterialsAndConsumablesTotal: "Raw materials and consumables, total",
      rawMaterialsAndServices: "Raw materials and services",
      rawMaterialsAndServicesTotal: "Raw materials and services, total",
      receivables: "receivables",
      reductionsInValue: "Reductions in value",
      representationExpenses: "Representation expenses",
      researchAndDevelopmentExpenses: "Research and development expenses",
      retairnedEarnings: "Retairned earnings (loss)",
      revaluationReserve: "Revaluation reserve",
      salesAndMarketingExpenses: "Sales and marketing expenses",
      shortterm: "Shortterm",
      shorttermCreditorsTotal: "Shortterm creditors, total",
      shorttermDeptorsTotal: "Shortterm debtors, total",
      shorttermEquipment: "Shortterm equipment",
      shorttermExpenses: "Expenses",
      socialSecurityExpenses: "Social security expenses",
      staffExpenses: "Staff expenses",
      staffExpensesTotal: "Staff expenses, total",
      stocks: "Stocks",
      submit: "Submit",
      subscribedCapital: "Subscribed capital",
      subtitle: "Subtitle",
      tangibleAssets: "Tangible assets",
      tangibleAssetsTotal: "Tangible assets, total",
      title: "Title",
      total: "Total",
      totalAmount: "Total amount",
      tradeCreditors: "Trade creditors",
      tradeDebtors: "Trade debtors",
      travelExpenses: "Travel expenses",
      turnoverNetSales: "Turnover (net sales)",
      turnoverTradeDebtors: "Turnover, trade debtors",
      variationsInStocks: "Variations in stocks",
      vat: "VAT",
      vatDebt: "Vat-debt",
      vatReceivables: "Vat-receivables",
      vechileExpenses: "Vechile expenses",
      wagesAndSalaries: "Wages and salaries",
      withdrawal: "Withdrawal"
    },
    fi: {
      admistrationExpenses: "Hallintokulut",
      appropriationsIncome: "Tilinpäätössiirrot (tuotto)",
      apartmentExpenses: "Toimitilakulut",
      appropriations: "Tilinpäätössiirtojen kertymä",
      appropriationsExpense: "Tilinpäätössiirrot (kulut)",
      assets: "Vastaavaa",
      assetsTotal: "Vastaavaa yhteensä",
      balanceSheet: "Tase",
      buildings: "Rakennukset ja rakennelmat",
      capital: "Oma pääoma",
      capitalAndReserves: "Oma pääoma",
      capitalAndReservesTotal: "Oma pääoma yhteensä",
      cashInHandAndInBank: "Rahat ja pankkisaamiset",
      cashOrBank: "Rahat",
      computerDeviceAndSoftware: "Atk-laite ja -ohjelmistokulut",
      creditors: "Vieras pääoma",
      creditorsTotal: "Vieras pääoma total",
      currentAssets: "Vaihtuvat vastaavat",
      currentAssetsTotal: "Vaihtuvat vastaavat, yhteensä",
      debtor: "Saatava",
      debtors: "Saatavat",
      debosit: "+",
      debositOrWithdrawal: "Kassa (+/-)",
      delete: "Poista",
      depreciationsAccordingToPlan: "Suunnitelman mukaiset poistot",
      depreciationsAndReductionsInValue: "Poistot ja arvonalentumiset",
      depreciationsAndReductionsInValueTotal: "Poistot ja arvonalentumiset, yhteensä",
      equityAndLiabilities: "Vastattavaa",
      equityAndLiabilitiesTotal: "Vastattavaa yhteensä",
      externalServices: "Ulkoiset palvelut",
      financialExpenses: "Rahoituskulut",
      financialIncome: "Rahoitustuotot",
      income: "Tuotto",
      incomeTaxes: "Tuloverot",
      intangibleAssets: "Aineettomat hyödykkeet",
      investments: "Sijoitukset",
      loanOrDebt: "Vieras pääoma",
      loans: "lainat",
      loansFromCreditInstitutions: "Lainojen lyhennykset",
      longterm: "Pitkäaikaiset",
      longtermExpenses: "Pysyvät vastaavat",
      machineryAndEquipment: "Koneet ja kalusto",
      nonCurrentAssets: "Pysyvät vastaavat",
      nonCurrentAssetsTotal: "Pysyvät vastaavat yhteensä",
      operatingProfitLoss: "Liikevoitto",
      optionalStaffExpenses: "Vapaaehtoiset henkilöstökulut",
      otherCreditors: "Muut velat",
      otherOperatingExpenses: "Liiketoiminnan muut kulut",
      otherOperatingExpensesTotal: "Liiketoiminnan muut kulut yhteensä",
      otherOperatingIncome: "Liiketoiminnan muut tuotot",
      otherReceivables: "Muut saatavat",
      otherReserves: "Muut rahastot",
      otherSocialSecurityExpenses: "Muut henkilöstösivukulut",
      passedData: "Syötetyt tiedot",
      pensionExpenses: "Eläkekulut",
      price: "Hinta",
      profitAndLossAccount: "Tuloslaskelma",
      profitLossBeforeAppropriationsAndTaxes: "Voitto ennen tp-siirtoja ja veroja",
      profitLossOfTheFinancialYear: "Tilikauden voitto",
      provisions: "Pakolliset varaukset",
      purchasesDuringTheFinancialYear: "Ostot tilikauden aikana",
      purchasesDuringTheFinancialYearTradeCreditors: "Ostot tilikauden aikana, velat",
      rawMaterialsAndConsumables: "Aineet, tarvikkeet ja tavarat",
      rawMaterialsAndConsumablesTotal: "Aineet, tarvikkeet ja tavarat, yhteensä",
      rawMaterialsAndServices: "Materiaalit ja palvelut",
      rawMaterialsAndServicesTotal: "Materiaalit ja palvelut yhteensä",
      receivables: "saatavat",
      reductionsInValue: "Arvonalentumiset",
      representationExpenses: "Edustuskulut",
      researchAndDevelopmentExpenses: "Tutkimus- ja kehityskulut",
      retairnedEarnings: "Edellisten tilikausien voitto",
      revaluationReserve: "Arvonkorotusrahasto",
      salesAndMarketingExpenses: "Myynti- ja markkinointikulut",
      shortterm: "Lyhytaikainen",
      shorttermCreditorsTotal: "Lyhytaikainen vieras pääoma yhteensä",
      shorttermDeptorsTotal: "Lyhytaikaiset saatavat yhteensä",
      shorttermEquipment: "Lyhytvaikutteiset kalustokulut",
      shorttermExpenses: "Kulut",
      socialSecurityExpenses: "Henkilöstösivukulut",
      staffExpenses: "Henkilöstökulut",
      staffExpensesTotal: "Henkilöstökulut yhteensä",
      stocks: "Vaihto-omaisuus (varasto)",
      submit: "jatka",
      subscribedCapital: "Osake-, osuus- tai muu oma pääoma",
      subtitle: "Alaotsikko",
      tangibleAssets: "Aineelliset hyödykkeet",
      tangibleAssetsTotal: "Aineelliset hyödykkeet yhteensä",
      title: "Otsikko",
      total: "Yhteensä",
      totalAmount: "Summa",
      tradeCreditors: "Ostovelat",
      tradeDebtors: "Myyntisaamiset",
      travelExpenses: "Matkustuskulut",
      turnoverNetSales: "Liikevaihto (myynti)",
      turnoverTradeDebtors: "Liikevaihto (myyntisaaminen)",
      variationsInStocks: "Varaston muutos",
      vat: "ALV",
      vatDebt: "ALV-velat",
      vatReceivables: "ALV-saamiset",
      vechileExpenses: "Ajoneuvokulut",
      wagesAndSalaries: "Palkat ja palkkiot",
      withdrawal: "-"
    },
    se: {
      admistrationExpenses: "Admistrationskostnader",
      appropriationsIncome: "Bokslutdispositioner (intänkte)",
      apartmentExpenses: "Lägenhetkostnader",
      appropriations: "Ackumulerade bokslutdispositioner",
      appropriationsExpense: "Bokslutdispositioner (kostnader)",
      assets: "Aktiva",
      assetsTotal: "Aktiva total",
      balanceSheet: "Balansräkning",
      buildings: "Byggnader och konstuktioner",
      capital: "Eget kapital",
      capitalAndReserves: "Eget kapital",
      capitalAndReservesTotal: "Capital and reserves, Total",
      cashInHandAndInBank: "Kassa och bank",
      cashOrBank: "Cash or bank",
      computerDeviceAndSoftware: "Dator och programvaror",
      creditors: "Främmande kapital",
      creditorsTotal: "Främmande kapital totalt",
      currentAssets: "Rörliga aktiva",
      currentAssetsTotal: "Rörliga aktiva, totalt",
      debtor: "Rörliga aktiva",
      debtors: "Fordringar",
      debosit: "Deposition",
      debositOrWithdrawal: "Deposition eller uttag",
      delete: "Radera",
      depreciationsAccordingToPlan: "Avskrivningar enligt plan",
      depreciationsAndReductionsInValue: "Avskrivningar och nedskrivningar",
      depreciationsAndReductionsInValueTotal: "Avskrivningar och nedskrivningar totalt",
      equityAndLiabilities: "Passiva",
      equityAndLiabilitiesTotal: "Passiva totalt",
      externalServices: "Köpta tjänster",
      financialExpenses: "Financiella kostnader",
      financialIncome: "Finansiella intänker",
      income: "Intänkte",
      incomeTaxes: "Inkomstskatt",
      intangibleAssets: "Immateriella tillgångar",
      investments: "Placeringar",
      loanOrDebt: "Främmande kapital",
      loans: "skulder",
      loansFromCreditInstitutions: "Skulder till kreditinstitut",
      longterm: "Långfristiga",
      longtermExpenses: "Bestående aktiva",
      machineryAndEquipment: "maskiner och inventarier",
      nonCurrentAssets: "Bestående aktiva",
      nonCurrentAssetsTotal: "Non-current assets total",
      operatingProfitLoss: "Rörelsevinst (förlust)",
      optionalStaffExpenses: "Frivilliga personalkostnader",
      otherCreditors: "Övriga skulder",
      otherOperatingExpenses: "Övriga rörelsekostnader",
      otherOperatingExpensesTotal: "Övriga rörelsekostnader totalt",
      otherOperatingIncome: "Övriga rörelseintänker",
      otherReceivables: "Övriga fordringar",
      otherReserves: "Övriga fonder",
      otherSocialSecurityExpenses: "Övriga lönebikostnader",
      passedData: "Passerade föremål",
      pensionExpenses: "Pensionkostnader",
      price: "Pris",
      profitAndLossAccount: "Resultaträkning",
      profitLossBeforeAppropriationsAndTaxes: "Vinst (förlust) före bokslutdispositioner och skatter",
      profitLossOfTheFinancialYear: "Räkenskapsperiodens vinst (förlust)",
      provisions: "Avsättningar",
      purchasesDuringTheFinancialYear: "Inköp under räkenskapsperioden",
      purchasesDuringTheFinancialYearTradeCreditors: "Purchases during the financial year, trade creditors",
      rawMaterialsAndConsumables: "Material och tjänster",
      rawMaterialsAndConsumablesTotal: "Raw materials and consumables, total",
      rawMaterialsAndServices: "Raw materials and services",
      rawMaterialsAndServicesTotal: "Raw materials and services, total",
      receivables: "fordringar",
      reductionsInValue: "Nedskrivningar",
      representationExpenses: "Representationskostnader",
      researchAndDevelopmentExpenses: "Forknings- och utvecklingskostnader",
      retairnedEarnings: "Balanserad vinst (förlust) från tidigare räkenskapsperioder",
      revaluationReserve: "Uppskrivningsfond",
      salesAndMarketingExpenses: "Försäljnings- och marknadsföringskostnader",
      shortterm: "Kortfristiga",
      shorttermCreditorsTotal: "Shortterm creditors, total",
      shorttermDeptorsTotal: "Shortterm debtors, total",
      shorttermEquipment: "Maskinkostnader",
      shorttermExpenses: "Kostnader",
      socialSecurityExpenses: "Lönebikostnader",
      staffExpenses: "Personalkostnader",
      staffExpensesTotal: "Personalkostnader totalt",
      stocks: "Omsättningstillgångar (produkter / varor)",
      submit: "Lämna",
      subscribedCapital: "Aktie- eller andelskapital eller annat motsvarande kapital",
      subtitle: "Undertitel",
      tangibleAssets: "Materiella tillgängar",
      tangibleAssetsTotal: "Tangible assets, total",
      title: "Titel",
      total: "Totalt",
      totalAmount: "Totalt belopp",
      tradeCreditors: "Leverantörsskulder",
      tradeDebtors: "Kundfordringar",
      travelExpenses: "Resekostnader",
      turnoverNetSales: "Omsättning",
      turnoverTradeDebtors: "Omsättning, kundfordringar",
      variationsInStocks: "Förändring av lager",
      vat: "Moms",
      vatDebt: "Moms-skulder",
      vatReceivables: "Moms-fordringar",
      vechileExpenses: "Fordonkostnader",
      wagesAndSalaries: "Löner och arvoden",
      withdrawal: "Uttag"
    }
  }

  constructor() { }

  getPack(lan){ return this.strings[lan]; }

}
